const listOfPerson = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "New York",
    age: 28,
    position: "Frontend Developer",
    experience: 4,
    skills: ["React", "TypeScript", "Next.js", "CSS"],
    description: "Passionate frontend developer who loves crafting interactive and accessible user interfaces.",
  },
  {
    firstName: "Emily",
    lastName: "Smith",
    city: "Los Angeles",
    age: 34,
    position: "UI/UX Designer",
    experience: 7,
    skills: ["Figma", "Adobe XD", "Design Systems", "User Research"],
    description: "Creative designer focused on improving user experience through empathy and simplicity.",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    city: "Chicago",
    age: 41,
    position: "Project Manager",
    experience: 12,
    skills: ["Agile", "Scrum", "Leadership", "Communication"],
    description: "Experienced PM who thrives on managing cross-functional teams and delivering projects on time.",
  },
  {
    firstName: "Sarah",
    lastName: "Williams",
    city: "Houston",
    age: 25,
    position: "Data Analyst",
    experience: 2,
    skills: ["Python", "SQL", "Tableau", "Excel"],
    description: "Data-driven thinker with a strong analytical mindset and a love for turning data into insights.",
  },
  {
    firstName: "David",
    lastName: "Brown",
    city: "Phoenix",
    age: 37,
    position: "Entrepreneur / Product Owner",
    experience: 10,
    skills: ["Product Strategy", "Market Research", "Innovation"],
    description: "Entrepreneur passionate about building digital products that make people's lives easier.",
  },
  {
    firstName: "Olivia",
    lastName: "Jones",
    city: "Philadelphia",
    age: 30,
    position: "Software Engineer",
    experience: 6,
    skills: ["JavaScript", "Node.js", "Express", "MongoDB"],
    description: "Full-stack engineer eager to contribute to scalable web applications and clean codebases.",
  },
  {
    firstName: "Sophia",
    lastName: "Martinez",
    city: "San Diego",
    age: 29,
    position: "Graphic Designer",
    experience: 5,
    skills: ["Photoshop", "Illustrator", "Branding", "Typography"],
    description: "Visual storyteller who believes design should be functional, beautiful, and meaningful.",
  },
  {
    firstName: "Liam",
    lastName: "Clark",
    city: "New York",
    age: 39,
    position: "Civil Engineer",
    experience: 14,
    skills: ["AutoCAD", "Project Planning", "Structural Design"],
    description: "Seasoned civil engineer passionate about building sustainable and efficient infrastructure.",
  },
  {
    firstName: "Ava",
    lastName: "Davis",
    city: "San Jose",
    age: 26,
    position: "Mobile App Developer",
    experience: 3,
    skills: ["React Native", "Swift", "Kotlin", "Firebase"],
    description: "App developer dedicated to creating seamless mobile experiences that users love.",
  },
  {
    firstName: "Benjamin",
    lastName: "Wright",
    city: "Dallas",
    age: 38,
    position: "Legal Consultant",
    experience: 13,
    skills: ["Contract Law", "Negotiation", "Compliance"],
    description: "Detail-oriented legal advisor helping startups navigate complex regulatory challenges.",
  },
  {
    firstName: "Chloe",
    lastName: "Nelson",
    city: "Houston",
    age: 28,
    position: "Social Worker",
    experience: 4,
    skills: ["Counseling", "Community Outreach", "Advocacy"],
    description: "Empathetic social worker with a passion for supporting families and empowering communities.",
  },
  {
    firstName: "Jackson",
    lastName: "Turner",
    city: "New York",
    age: 39,
    position: "Business Analyst",
    experience: 9,
    skills: ["Business Intelligence", "Process Optimization", "Excel"],
    description: "Analyst who enjoys using data-driven insights to improve organizational efficiency.",
  },
  {
    firstName: "Mia",
    lastName: "Hall",
    city: "Houston",
    age: 27,
    position: "Interior Designer",
    experience: 5,
    skills: ["AutoCAD", "3D Modeling", "Color Theory"],
    description: "Creative interior designer with a passion for modern spaces and client satisfaction.",
  },
  {
    firstName: "Elijah",
    lastName: "Cox",
    city: "Dallas",
    age: 36,
    position: "Marketing Director",
    experience: 11,
    skills: ["Digital Marketing", "SEO", "Brand Strategy"],
    description: "Strategic marketer with a track record of driving growth through creative campaigns.",
  },
  {
    firstName: "Scarlett",
    lastName: "Ward",
    city: "San Jose",
    age: 34,
    position: "Brand Designer",
    experience: 8,
    skills: ["Brand Identity", "Motion Graphics", "Typography"],
    description: "Designer who loves crafting cohesive visual identities and brand storytelling.",
  },
];

export default listOfPerson;
