const SkillsList = [
  "React",
  "TypeScript",
  "Next.js",
  "CSS",
  "Figma",
  "Adobe XD",
  "Design Systems",
  "User Research",
  "Agile",
  "Scrum",
  "Leadership",
  "Communication",
  "Python",
  "SQL",
  "Tableau",
  "Excel",
  "Product Strategy",
  "Market Research",
  "Innovation",
  "JavaScript",
  "Node.js",
  "Express",
  "MongoDB",
  "Photoshop",
  "Illustrator",
  "Branding",
  "Typography",
  "AutoCAD",
  "Project Planning",
  "Structural Design",
  "React Native",
  "Swift",
  "Kotlin",
  "Firebase",
  "Contract Law",
  "Negotiation",
  "Compliance",
  "Counseling",
  "Community Outreach",
  "Advocacy",
  "Business Intelligence",
  "Process Optimization",
  "Excel",
  "AutoCAD",
  "3D Modeling",
  "Color Theory",
  "Digital Marketing",
  "SEO",
  "Brand Strategy",
  "Brand Identity",
  "Motion Graphics",
  "Typography",
];

export default SkillsList;
